config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :rooms do
    resources :messages
  end
  root 'pages#home'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get 'user/:id', to: 'users#show', as: 'user'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/joinable.rb
class Joinable < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  has_many_attached :attachments, dependent: :destroy

  def image?(file)
    file.to_s.include?('.gif') or file.to_s.include?('.png') or file.to_s.include?('.jpg')
  end

  def chat_attachment(index)
    target = attachments[index]

    # binding.pry

    return unless attachments.attached?

    if target.image?
      target.variant(resize_to_limit: [150, 150]).processed
    elsif target.video?
      target.variant(resize_to_limit: [150, 150]).processed
    end
  end

  after_create_commit { broadcast_append_to room }

  before_create :confirm_participants

  def confirm_participants
    return unless room.private

    is_participant = Participant.where(user_id: user.id, room_id: room.id).first
    throw :abort unless is_participant
  end
end

app/models/participant.rb
# frozen_string_literal: true

class Participant < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  validates_uniqueness_of :name

  scope :public_rooms, -> { where(private: false) }

  has_many :messages

  has_many :participants, dependent: :destroy

  after_create_commit { broadcast_if_public }

  def broadcast_if_public
    broadcast_append_to 'rooms' unless private
  end

  def self.create_private_room(users, room_name)
    single_room = Room.create(name: room_name, private: true)

    users.each do |user|
      Participant.create(user_id: user.id, room_id: single_room.id)
    end
    single_room
  end

  def participant?(room, user)
    room.participants.where(user: user).exists?
    # Participant.where(user_id: user.id,room_id: room.id).exists?
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :email,:password
  validates_length_of :email, :maximum =>50
  
  scope :all_except, ->(user) { where.not(id: user) }

  has_many :messages, dependent: :destroy

  after_create_commit { broadcast_append_to 'users' }

  after_update_commit { broadcast_update }

  after_commit :add_default_avatar, on: %i[create update]

  enum status: %i[offline away online]

  has_one_attached :avatar do |image|
    image.variant :avatar_thumbnail, resize_to_limit: [100, 100]
    image.variant :chat_avatar, resize_to_limit: [100, 100]
  end

  def avatar_thumbnail
    # return if avatar.attached?
    avatar.variant(resize_to_limit: [150, 150]).processed
  end

 

  # def chat_avatar
  #   avatar.variant(resize_to_limit: [50, 50]).processed
  # end

  def broadcast_update
    # debugger
    broadcast_replace_to 'user_status', partial: 'users/status', user: self
  end

  def status_to_css
    case status
    when 'online'
      'background-color: green'
    when 'away'
      'background-color: yellow'
    when 'offline'
      'background-color: gray'
    else
      'background-color: red'
    end
  end

  private

  def add_default_avatar
    return if avatar.attached?

    avatar.attach(
      io: File.open(Rails.root.join('app', 'assets', 'images', 'default_profile.jpg')),
      filename: 'default_profile.jpg'
    )
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Application Controller

class ApplicationController < ActionController::Base
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

# This Controls The Messages

class MessagesController < ApplicationController
  def create
    @message = current_user.messages.create(body: msg_params[:body], room_id: params[:room_id], attachments: msg_params[:attachments])
  end

  private

  def msg_params
    params.require(:message).permit(:body, attachments: [])
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

# Controller: pages

class PagesController < ApplicationController
  after_action :set_status
  def home; end

  def set_status
    current_user&.update!(status: User.statuses[:offline])
  end
end
  

app/controllers/room_controller.rb
class RoomController < ApplicationController
  before_action :authenticate_user!


  def index
    @rooms = Room.public_rooms;
    @users = User.all_except(current_user);
  end


end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

# Controller sets The Current Status and Rooms seraches

class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_status

  def index
    @room = Room.new
    @rooms = Room.public_rooms
    @users = User.all_except(current_user).joins(:messages).order(updated_at: :desc)
    render 'index'
  end

  def show
    @room = Room.new
    @rooms = Room.public_rooms
    @users = User.all_except(current_user).joins(:messages).order(updated_at: :desc)
    # User.joins(:messages).order(updated_at: :desc)
    @single_room = Room.find(params[:id])
    @message = Message.new
    @messages = @single_room.messages.order(created_at: :asc)

    render 'index'
  end

  def create
    debugger
    @room = Room.create(room_params)
  end

  private

  def room_params
    params.require(:room).permit(:name)
  end

  def set_status
    current_user&.update!(status: User.statuses[:online])
  end
end

app/controllers/turbo_devise_controller.rb
# frozen_string_literal: true
# Custom COnfiguration For Turbo Device

# class TurboDeviseController < ApplicationController
#   class Responder < ActionController::Responder
#     def to_turbo_stream
#       controller.render(options.merge(formats: :html))
#     rescue ActionView::MissingTemplate => e
#       if get?
#         raise e
#       elsif has_errors? && default_action
#         render rendering_options.merge(formats: :html, status: :unprocessable_entity)
#       else
#         redirect_to navigation_location
#       end
#     end
#   end

#   self.responder = Responder
#   respond_to :html, :turbo_stream
# end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

module Users
  class UnlocksController < Devise::UnlocksController
    # GET /resource/unlock/new
    # def new
    #   super
    # end

    # POST /resource/unlock
    # def create
    #   super
    # end

    # GET /resource/unlock?unlock_token=abcdef
    # def show
    #   super
    # end

    # protected

    # The path used after sending unlock password instructions
    # def after_sending_unlock_instructions_path_for(resource)
    #   super(resource)
    # end

    # The path used after unlocking the resource
    # def after_unlock_path_for(resource)
    #   super(resource)
    # end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Custom Controller For UsersSHow

class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @users = User.all_except(current_user)

    @room = Room.new
    @rooms = Room.public_rooms

    @room_name = get_name(@user, current_user)
    @single_room = Room.where(name: @room_name).first || Room.create_private_room([@user, current_user], @room_name)

    @message = Message.new
    @messages = @single_room.messages.order(created_at: :asc)
    render 'rooms/index'
  end


  def get_name(user1, user2)
    users = [user1, user2].sort
    "private_#{users[0].id}_#{users[1].id}"
  end
  
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/messages_helper.rb
# frozen_string_literal: true

module MessagesHelper
end

app/helpers/pages_helper.rb
# frozen_string_literal: true

module PagesHelper
end

app/helpers/room_helper.rb
# frozen_string_literal: true

module RoomHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/layouts/_navbar.html.erb
<nav class="bg-gray-800">
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="relative flex h-16 items-center justify-between">
      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
        <!-- Mobile menu button-->
        <button type="button" class="inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-700 hover:text-white focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <!--
            Icon when menu is closed.

            Heroicon name: outline/bars-3

            Menu open: "hidden", Menu closed: "block"
          -->
          <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
          <!--
            Icon when menu is open.

            Heroicon name: outline/x-mark

            Menu open: "block", Menu closed: "hidden"
          -->
          <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex flex-shrink-0 items-center">
          <img class="block h-8 w-auto lg:hidden" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">
          <img class="hidden h-8 w-auto lg:block" src="https://tailwindui.com/img/logos/mark.svg?color=indigo&shade=500" alt="Your Company">
        </div>
        <div class="hidden sm:ml-6 sm:block">
          <div class="flex space-x-4">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <a href="/" class="bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium
            hover:bg-violet-600 active:bg-violet-700 focus:outline-none focus:ring focus:ring-violet-300
            
            " aria-current="page">Dashboard</a>

            <%# <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Team</a> %>

            <%# <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Projects</a> %>

            <%# <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">Calendar</a> %>
          </div>
        </div>
      </div>
      <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
        <button type="button" class="rounded-full bg-gray-800 p-1 text-gray-400 hover:text-white focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800">
          <span class="sr-only">View notifications</span>
          <!-- Heroicon name: outline/bell -->
          <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
          </svg>
        </button>

        <!-- Profile dropdown -->
          <div class="relative ml-3" data-controller="handler" >
            <div data-action="click->handler#toggle">
              <button type="button" class="flex rounded-full bg-gray-800 text-sm focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
                <span class="sr-only">Open user menu</span>
                <% if user_signed_in?%>
                <%= image_tag(current_user.avatar.variant(resize_to_limit: [100, 100]),class: "h-8 w-8 rounded-full") if current_user.avatar.attached? %>
                <% end %>
              </button>
            </div>

          <!--
            Dropdown menu, show/hide based on menu state.

            Entering: "transition ease-out duration-100"
              From: "transform opacity-0 scale-95"
              To: "transform opacity-100 scale-100"
            Leaving: "transition ease-in duration-75"
              From: "transform opacity-100 scale-100"
              To: "transform opacity-0 scale-95"
          -->
            <div data-handler-target="toggleable" class="hidden absolute right-0 z-10 mt-2 w-48 origin-top-right rounded-md bg-white py-1 shadow-lg ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">
              <!-- Active: "bg-gray-100", Not Active: "" -->
              <a href="/users/edit" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-0">Your Profile</a>
              <%=button_to "Sign out",destroy_user_session_path, method: :delete , class: "block px-4 py-2 text-sm text-gray-700"%>
              <%# <a href="${destroy_user_session_path}" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-2">Sign out</a> %>
            </div>
        </div>

      </div>
    </div>
  </div>

  <!-- Mobile menu, show/hide based on menu state. -->
  <div class="sm:hidden" id="mobile-menu">
    <div class="space-y-1 px-2 pt-2 pb-3">
      <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
      <a href="/" class="bg-gray-900 text-white block px-3 py-2 rounded-md text-base font-medium" aria-current="page">Dashboard</a>

      <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium">Team</a>

      <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium">Projects</a>

      <a href="#" class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium">Calendar</a>
    </div>
  </div>
</nav>

app/views/layouts/_new_form.html.erb
<%= form_with(model: [@single_room, @message  ],remote: true) do |f|%>
  <%= f.text_field :body, id: 'chat-text', autocomplete: 'off'%>
  <%= f.submit data: {disable_with: false} class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 border border-blue-700 rounded"%>

app/views/layouts/_new_message_form.html.erb
<div class = "form-group msg-form">
  <%= form_with(model: [@single_room, @message], remote: true, class: 'd-flex', data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset"} ) do |f| %>
 
  <div id = "attachment-previews"
  data-controller = "message-preview"
  data-action="message-preview#preview">
  </div>
 
  <div class = "image-upload">
    <label for="message_attachments">
      <i class = "bi bi-plus-circle upload-button"></i>
    </label>
    <%= f.file_field(:attachments,multiple: true, data:{controller: "message-preview", action:"change->message_preview#preview"})%>
  </div>
  <%= f.text_field :body, id: 'chat-text', class: 'bg-white text-gray-800 border border-gray-200 rounded msg-content', automcomlete: "off" %>
  <%= f.submit "Send",
  data: {disable_with: false, controller: "message-preview",
  action: "click->message_preview#clearPreviews"},
  class: "inline-block align-middle text-center select-none border font-normal whitespace-no-wrap rounded py-1 px-3 leading-normal no-underline bg-blue-600 text-white hover:bg-blue-600"
  %>
  <%end%>
  </div>

app/views/layouts/_new_room_form.html.erb
<%= form_with(model: @room, remote: true) do |f|%>
  <%= f.text_field :name, autocomplete: "off"%>
  <%= f.submit data: {disable_with: false} %>

<%end%>

app/views/layouts/_new_room_form_message.html.erb
<% if current_user.admin?%>
<%= form_with(model: @room, remote: true, class: 'd-flex',data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset"}) do |f|%>
  <%= f.text_field :name, class: 'block appearance-none w-full py-1 px-2 mb-1 text-base leading-normal bg-white text-gray-800 border border-gray-200 rounded',autocomplete: 'off'%>
  <%= f.submit data: {turbo: false}, class: 'inline-block align-middle text-center select-none border font-normal whitespace-no-wrap rounded py-1 px-3 leading-normal no-underline bg-blue-600 text-white hover:bg-blue-600
' %>
<%end%>

<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chatapplication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <!-- CSS only -->
<%# <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous"> %>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">

<!-- JavaScript Bundle with Popper -->
<%# <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script> %>

    <%= javascript_importmap_tags %>

    <style>
     <%= ".msg-#{current_user&.id}" %> {
      background-color: #007bff !important;
      padding: 10px;
      }
      <%= ".cont-#{current_user&.id}" %> {
        display: flex;
        justify-content: flex-end
      } 
    </style>
  </head>

  <body>
    <%= render "layouts/navbar"%>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<section class="bg-gray-900 text-white">
  <div
    class="mx-auto max-w-screen-xl px-4 py-32 lg:flex lg:h-screen lg:items-center"
  >
    <div class="mx-auto max-w-3xl text-center">
      <h1
        class="bg-gradient-to-r from-green-300 via-blue-500 to-purple-600 bg-clip-text text-3xl font-extrabold text-transparent sm:text-5xl"
      >
        Understand Relations

        <span class="sm:block"> Increase Conversion. </span>
      </h1>

      <% if current_user %>
        <%=link_to"Start Chat",rooms_path,class:"my-3 block w-full rounded border border-blue-600 bg-blue-600 px-12 py-3 text-sm font-medium text-white hover:bg-transparent hover:text-white focus:outline-none focus:ring active:text-opacity-75 sm:w-auto"%>
      <%else%>
      <p class="mx-auto mt-4 max-w-xl sm:text-xl sm:leading-relaxed">
        What makes our product work is the way we're tightly focused on messaging and being as SMS replacement.
      </p>

      <div class="mt-8 flex flex-wrap justify-center gap-4">
      <%=link_to"Get Started",new_user_registration_path,class:"block w-full rounded border border-blue-600 bg-blue-600 px-12 py-3 text-sm font-medium text-white hover:bg-transparent hover:text-white focus:outline-none focus:ring active:text-opacity-75 sm:w-auto"%>
      <%=link_to "Login",new_user_session_path,class:"block w-full rounded border border-blue-600 px-12 py-3 text-sm font-medium text-white hover:bg-blue-600 focus:outline-none focus:ring active:bg-blue-500 sm:w-auto" %>
      <% end %>
      </div>
    </div>
  </div>
</section>