config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :rooms do
    resources :messages
  end
  root 'pages#home'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get 'user/:id', to: 'users#show', as: 'user'
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  validates_uniqueness_of :name

  scope :public_rooms, -> { where(private: false) }

  has_many :messages

  has_many :participants, dependent: :destroy

  after_create_commit { broadcast_if_public }

  def broadcast_if_public
    broadcast_append_to 'rooms' unless private
  end

  def self.create_private_room(users, room_name)
    single_room = Room.create(name: room_name, private: true)

    users.each do |user|
      Participant.create(user_id: user.id, room_id: single_room.id)
    end
    single_room
  end

  def participant?(room, user)
    room.participants.where(user: user).exists?
    # Participant.where(user_id: user.id,room_id: room.id).exists?
  end
end

app/controllers/room_controller.rb
class RoomController < ApplicationController
  before_action :authenticate_user!


  def index
    @rooms = Room.public_rooms;
    @users = User.all_except(current_user);
  end


end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

# Controller sets The Current Status and Rooms seraches

class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_status

  def index
    @room = Room.new
    @rooms = Room.public_rooms
    @users = User.all_except(current_user).joins(:messages).order(updated_at: :desc)
    render 'index'
  end

  def show
    @room = Room.new
    @rooms = Room.public_rooms
    @users = User.all_except(current_user).joins(:messages).order(updated_at: :desc)
    # User.joins(:messages).order(updated_at: :desc)
    @single_room = Room.find(params[:id])
    @message = Message.new
    @messages = @single_room.messages.order(created_at: :asc)

    render 'index'
  end

  def create
    debugger
    @room = Room.create(room_params)
  end

  private

  def room_params
    params.require(:room).permit(:name)
  end

  def set_status
    current_user&.update!(status: User.statuses[:online])
  end
end

app/helpers/room_helper.rb
# frozen_string_literal: true

module RoomHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_joinable_link.html.erb
<% if current_user.has_joined_room(room) %>
  <%debugger%>
    <%= link_to leave_room_path(room),method: :delete,data: {turbo: "false"} do%>
      <i class = "bi bi-dash-square room-leave-link-icon"></i>
    <%end%>
<%else%>
    <%= link_to join_room_path(room),method: :delete do %>
      <i class = "bi bi-plus-square room-join-link-icon"></i>
      <%end%>
<% end %>

app/views/rooms/_last_message.html.erb
<% unless last_message.nil? %>
  <div class = "row">
    <div class = "col-12 flex items-center justify-between">
      <em class = "last-message">
      <%= "#{last_message.user.email} sent a message".truncate(40)%>
      </em>
      <em class = "last-message">
        <%= "#{time_ago_in_words(last_message.created_at)} ago"%>
      </em>
    </div>
  </div>
<%end%>

app/views/rooms/_room.html.erb
<% turbo_frame_tag dom_id(room) do %>
  <%= render 'rooms/room_container',
  room: room,
  last_message: last_message,
  user: user
  %>
<% end %>

app/views/rooms/_room_container.html.erb
<li class ="relative block py-3 px-6 -mb-px border border-r-0 border-l-0 border-gray-300 no-underline user_list_item">
  <div class = "row">
    <div class = "col-12 flex items-center justify-between">
        <%= link_to room.name, room_path(room,name_search: params[:name_search]) ,data: {turbo: false},class: "ms-2 me-auto"%>
        <%= render 'rooms/joinable_link',room: room%>
    </div>
  </div>

  <%= turbo_frame_tag [dom_id(room), "last_message"] do %>
    <%= render "rooms/last_message",room: room, user: user, last_message: last_message%>
  <% end %>
</li>

app/views/rooms/_rooms.html.erb
<% rooms.each do |room| %>
  <%= render 'rooms/room',
  room: room,
  last_message: room.latest_message,
  user: user
  %>
<% end %>

app/views/rooms/_search_form.html.erb
<%= form_with url: search_rooms_path, 
    method: :post, 
    data: {controller: "debounce"}, 
    id: "room_search_form" do |form| %>
<%= form.search_field :name_search, 
    value: params[:name_search],
    class: 'room_search_field',
    placeholder: "Search Rooms To Join..",
    data: {action: "input->debounce#search"}    %>
  
  <%end%>

  <div id ="search_result">
    <%= render 'rooms/search_results',rooms: @rooms%>
  </div>

app/views/rooms/_search_results.html.erb
<% rooms.each do |room|%>
<li class ="bg-black relative block py-3 px-6 -mb-px border border-r-0 border-l-0 border-gray-300 no-underline flex items-center justify-between user_list_item">
<%= link_to room.name,room_path(id: room.id,name_search: params[:name_search]),data: {turbo: "false"}%>

<%= render "rooms/joinable_link",room: room%>
</li>
<%end%>

app/views/rooms/index.html.erb
<%= turbo_frame_tag "appearance_channel"%>
<div id = "appearance_channel"></div>
<div id="chatroom_container" class="flex flex-wrap  bg-gray-900 text-gray-100">
  <div id="side_panel" class="md:w-1/3 pr-4 pl-4 sm:w-1/3 pr-4 pl-4">
<li class ="relative block py-3 px-6 -mb-px border border-r-0 border-l-0 border-gray-300 no-underline flex items-center justify-between user_list_item">
    <div class = 'icon-container'>
  <%= link_to image_tag(current_user.avatar.variant(resize_to_limit: [100, 100]),class: 'chat_pfp'),current_user%>
  <%= turbo_stream_from "user_status"%>

  <div>
  <%= render "users/status",user: current_user%>
  </div>
</div>
<div class = 'ms-2 me-auto username'>
<%= current_user.email%>
</div>
</li>
    <h4> Users </h4>
    <%= turbo_stream_from "users" %>
    <div id="users/user">
      <%= render @users %>
    </div>
    <h4> Rooms </h4>
    <%= turbo_stream_from "rooms" %>
    <%= render 'layouts/new_room_form_message' %>
    <%= render 'rooms/search_form'%>
    <div id="rooms/room">
      <%= render "rooms/rooms", rooms: @joined_rooms,user: current_user %>
    </div>
  </div>



  <div id="room_container"
  class="md:w-2/3 pr-4 pl-4 sm:w-2/3 pr-4 pl-4 bg-gray-900 text-gray-100">
    <% if @single_room %>
      <div id="single_room">
        <h4 class="text-center"> <%= @user&.email || @single_room.name %> </h4>
        <%= turbo_stream_from @single_room %>
        <div id="messages" data-controller="scroll">
          <%= render @messages %>
        </div>
        <%= render 'layouts/new_message_form' %>
      </div>
    <% end %>
  </div>